import { Achievement } from '@/types/user';

export const ACHIEVEMENTS: Achievement[] = [
    // --- SHARED BADGES (8) ---
    {
        id: 'onboarded',
        name: 'Initiate',
        description: 'Select your role and begin your journey.',
        icon: 'UserCheck',
        xp: 100,
        condition: (p) => !!p.role,
    },
    {
        id: 'scholar',
        name: 'Scholar',
        description: 'Read 10 documentation files.',
        icon: 'BookOpen',
        xp: 200,
        condition: (p) => p.stats.docsRead >= 10,
    },
    {
        id: 'librarian',
        name: 'Librarian',
        description: 'Deep dive: Read 50 documentation files.',
        icon: 'Library',
        xp: 1000,
        condition: (p) => p.stats.docsRead >= 50,
    },
    {
        id: 'streak_3',
        name: 'Consistent',
        description: 'Maintain a 3-day activity streak.',
        icon: 'Zap',
        xp: 300,
        condition: (p) => p.stats.streak >= 3,
    },
    {
        id: 'streak_7',
        name: 'Addicted',
        description: 'Maintain a 7-day activity streak.',
        icon: 'Flame',
        xp: 1000,
        condition: (p) => p.stats.streak >= 7,
    },
    {
        id: 'search_pro',
        name: 'Finder',
        description: 'Perform 20 successful searches.',
        icon: 'Search',
        xp: 200,
        condition: (p) => p.stats.searchCount >= 20,
    },
    {
        id: 'vault_keeper',
        name: 'Vault Keeper',
        description: 'Unlock the Admin Terminal.',
        icon: 'Shield',
        xp: 500,
        condition: (_, ctx) => ctx?.path === '/admin',
    },
    {
        id: 'marathon',
        name: 'Marathoner',
        description: 'Read a document for over 5 minutes.',
        icon: 'Clock',
        xp: 500,
        condition: (p) => p.stats.longReads >= 1,
    },

    // --- FIELD OPS / THE SELLER (8) ---
    {
        id: 'market_watcher',
        name: 'Market Watcher',
        description: 'Study 10 Research documents.',
        icon: 'LineChart',
        xp: 500,
        role: 'field_ops',
        condition: (p) => p.stats.researchRead >= 10,
    },
    {
        id: 'closer',
        name: 'The Closer',
        description: 'Master the Sales Playbooks (Read 5 Sales files).',
        icon: 'DollarSign',
        xp: 1000,
        condition: (p) => p.stats.salesRead >= 5, // Shared check, but themed for Ops
    },
    {
        id: 'lead_gen',
        name: 'Lead Prospector',
        description: 'Review the CRM and lead generation strategy.',
        icon: 'Users',
        xp: 500,
        role: 'field_ops',
        condition: (_, ctx) => ctx?.path?.includes('crm'),
    },
    {
        id: 'deal_maker',
        name: 'Deal Maker',
        description: 'Study the final pricing and closing phase.',
        icon: 'CheckCircle',
        xp: 750,
        role: 'field_ops',
        condition: (_, ctx) => ctx?.path?.includes('closing'),
    },
    {
        id: 'branding_pro',
        name: 'Brand Custodian',
        description: 'Align with the brand guidelines.',
        icon: 'Palette',
        xp: 400,
        role: 'field_ops',
        condition: (_, ctx) => ctx?.path?.includes('brand'),
    },
    {
        id: 'content_king',
        name: 'Content King',
        description: 'Review 5 Marketing content pieces.',
        icon: 'PenTool',
        xp: 600,
        role: 'field_ops',
        condition: (p) => p.stats.marketingRead >= 5,
    },
    {
        id: 'pitch_perfect',
        name: 'Pitch Perfect',
        description: 'Master the elevator pitch and deck.',
        icon: 'Presentation',
        xp: 800,
        role: 'field_ops',
        condition: (_, ctx) => ctx?.path?.includes('pitch'),
    },
    {
        id: 'ops_guru',
        name: 'Ops Guru',
        description: 'Read the Daily Operations manual.',
        icon: 'Zap',
        xp: 500,
        role: 'field_ops',
        condition: (_, ctx) => ctx?.path?.includes('operations'),
    },

    // --- STRATEGY ARCH / THE BUILDER (8) ---
    {
        id: 'visionary',
        name: 'Visionary',
        description: 'Deep dive into 10 Strategy files.',
        icon: 'Telescope',
        xp: 500,
        role: 'strategy_arch',
        condition: (p) => p.stats.strategyRead >= 10,
    },
    {
        id: 'architect',
        name: 'System Architect',
        description: 'Study the core technical specifications.',
        icon: 'Server',
        xp: 1000,
        role: 'strategy_arch',
        condition: (_, ctx) => ctx?.path?.includes('technical'),
    },
    {
        id: 'optimizer',
        name: 'Performance Freak',
        description: 'Study the scalability and performance docs.',
        icon: 'Activity',
        xp: 750,
        role: 'strategy_arch',
        condition: (_, ctx) => ctx?.path?.includes('performance'),
    },
    {
        id: 'security_first',
        name: 'Locksmith',
        description: 'Analyze security protocols and Clerk auth.',
        icon: 'Lock',
        xp: 800,
        role: 'strategy_arch',
        condition: (_, ctx) => ctx?.path?.includes('security'),
    },
    {
        id: 'graph_master',
        name: 'Mapping Expert',
        description: 'Understand the Knowledge Graph architecture.',
        icon: 'GitNetwork',
        xp: 600,
        role: 'strategy_arch',
        condition: (_, ctx) => ctx?.path?.includes('graph'),
    },
    {
        id: 'api_pioneer',
        name: 'API Pioneer',
        description: 'Study the backend integration layers.',
        icon: 'Webhook',
        xp: 700,
        role: 'strategy_arch',
        condition: (_, ctx) => ctx?.path?.includes('api'),
    },
    {
        id: 'scaling_king',
        name: 'Scale King',
        description: 'Review the 12-month scaling roadmap.',
        icon: 'ArrowUpRight',
        xp: 900,
        role: 'strategy_arch',
        condition: (_, ctx) => ctx?.path?.includes('roadmap'),
    },
    {
        id: 'frameworker',
        name: 'Template Master',
        description: 'Study the standard framework templates.',
        icon: 'Layers',
        xp: 500,
        role: 'strategy_arch',
        condition: (_, ctx) => ctx?.path?.includes('framework'),
    },
];
